apiVersion: v1
kind: Template
labels:
  template: pets-deployment
metadata:
  name: pets-demo
  annotations:
    description: Deployment template for Pet photo sharing app
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: mongo
      name: mongo
    spec:
      replicas: 1
      selector:
        app: mongo
        deploymentconfig: mongo
      template:
        metadata:
          labels:
            app: mongo
            deploymentconfig: mongo
        spec:
          containers:
            - env:
                - name: MONGO_INITDB_DATABASE
                  value: pets
              image: mongo:3
              imagePullPolicy: IfNotPresent
              name: mongo
              ports:
                - containerPort: 27017
                  protocol: TCP
              volumeMounts:
                - mountPath: /data/configdb
                  name: mongo-cfg
                - mountPath: /data/db
                  name: mongo-data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          volumes:
            - emptyDir: {}
              name: mongo-cfg
            - emptyDir: {}
              name: mongo-data
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: Mongodb service
      labels:
        application: Pets
      name: mongo-service
    spec:
      ports:
      - name: mongo
        port: 27017
        targetPort: 27017
      selector:
        app: mongo
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: api-server
      name: api-server
    spec:
      replicas: 1
      selector:
        app: api-server
        deploymentconfig: api-server
      template:
        metadata:
          labels:
            app: api-server
            deploymentconfig: api-server
        spec:
          containers:
            - env:
                - name: DB_HOST
                  value: mongo-service
              image: vnguyen/pets-api-server:latest
              imagePullPolicy: IfNotPresent
              name: pets-api-server
              ports:
                - containerPort: 3005
                  protocol: TCP
          dnsPolicy: ClusterFirst
          restartPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: API server
      labels:
        application: Pets
      name: api-server
    spec:
      ports:
      - name: http
        port: 3005
        targetPort: 3005
      selector:
        app: api-server
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: api-server
      name: api-server
    spec:
      port:
        targetPort: http
      to:
        kind: Service
        name: api-server
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: media-server
      name: media-server
    spec:
      replicas: 1
      selector:
        app: media-server
        deploymentconfig: media-server
      template:
        metadata:
          labels:
            app: media-server
            deploymentconfig: media-server
        spec:
          containers:
            - image: vnguyen/pets-media-server:latest
              imagePullPolicy: IfNotPresent
              name: pets-media-server
              ports:
                - containerPort: 8081
                  protocol: TCP
          dnsPolicy: ClusterFirst
          restartPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: Media server
      labels:
        application: Pets
      name: media-server
    spec:
      ports:
      - name: http
        port: 8081
        targetPort: 8081
      selector:
        app: media-server
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: media-server
      annotations:
        template.openshift.io/expose-uri: "http://{.spec.host}"
      name: media-server
    spec:
      port:
        targetPort: http
      to:
        kind: Service
        name: media-server
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: frontend
      name: frontend
    spec:
      replicas: 1
      selector:
        app: frontend
        deploymentconfig: frontend
      template:
        metadata:
          labels:
            app: frontend
            deploymentconfig: frontend
        spec:
          containers:
            - env:
              - name: API_HOST
                value: 'http://api-server-${NAMESPACE}.${CLUSTER_DOMAIN}'
              - name: MEDIA_HOST
                value: 'http://media-server-${NAMESPACE}.${CLUSTER_DOMAIN}'
              image: vnguyen/pets-frontend:latest
              imagePullPolicy: IfNotPresent
              name: pets-frontend
              ports:
                - containerPort: 3000
                  protocol: TCP
          dnsPolicy: ClusterFirst
          restartPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: Web frontend
      labels:
        application: Pets
      name: frontend
    spec:
      ports:
      - name: http
        port: 3000
        targetPort: 3000
      selector:
        app: frontend
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: frontend
      name: frontend
    spec:
      port:
        targetPort: http
      to:
        kind: Service
        name: frontend
parameters:
- description: Cluster public domain for external route
  name: CLUSTER_DOMAIN
  required: true
  value: openshift.example.com
- description: Current project name
  name: NAMESPACE
  required: true


